# Generated by Django 6.0.2 on 2026-03-04 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0002_remove_auditlog_file_uploadedfile_validationresult_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
