# Generated by Django 6.0.2 on 2026-03-04 15:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("automation", "0003_uploadedfile_original_filename"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="uploadedfile",
            name="original_filename",
        ),
    ]
