# Generated by Django 6.0.2 on 2026-04-20 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0006_alter_uploadedfile_style_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='column_mappings',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
