# Generated by Django 6.0.2 on 2026-04-23 03:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0007_alter_uploadedfile_column_mappings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='file_status',
            field=models.CharField(default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='trash_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
