# Generated by Django 6.0.2 on 2026-04-23 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0008_uploadedfile_deleted_at_uploadedfile_deleted_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='is_mapping_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
