# Generated by Django 6.0.2 on 2026-04-23 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0009_uploadedfile_is_mapping_confirmed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='is_mapping_confirmed',
        ),
    ]
