# Generated by Django 6.0.2 on 2026-04-23 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0010_remove_uploadedfile_is_mapping_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='is_mapping_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
